#!/bin/bash

if [ $1 -gt $2 ];
then
	echo "Parâmetro 1 maior"
else
	echo "Parâmetro 2 maior"
fi

somador=$(($1+$2))
echo "Soma: $somador "

#Nota:  Para fazer um cálculo na linha de comando é necessário usar o comando “expr” ou a sintaxe $((operações))
#Exemplo: $ expr 20 + 05 ou $((var+2-outra_var))
